version: '2'

services:
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        links: 
            - php
            - phpmyadmin
        networks:
            - default
        restart: always

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./code:/code
        links:
            - mysql
        networks:
            - default
        restart: always

    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports: 
            - 8081:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        restart: always