version: '2'

services:
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./env/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./code:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
